server:
  port: 8080

#日志处理
logging:
  level:
    org.activiti: debug #开启activiti日志

spring:
  #应用名
  application:
    name: learn-activiti

  #数据源
  datasource:
    name: activiti
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root@

  #响应解析
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    parser:
      allow_unquoted_control_chars: true
      allow_single_quotes: true

